name: gallery
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.7.1
  get: 4.6.1
  flutter: 
    sdk: flutter
  url_launcher: ^6.0.20
  font_awesome_flutter: ^10.1.0
  user_profile_avatar: ^0.1.0
  simple_star_rating: ^0.0.3
  native_notify: ^0.0.12
  http: ^0.13.4






dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

